import { useState, useEffect, useMemo, useRef } from "react";
import { OrderItem } from "@/types/product";
import { Trash2, ShoppingCart, Plus, Minus, X, Info, Receipt, CheckCircle, Banknote, Smartphone, Tag, Edit2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { PaymentDetails } from "./PaymentDialog";
import { useMySQLSync } from "@/hooks/useMySQLSync";

interface OrderSidebarProps {
  items: OrderItem[];
  onRemoveItem: (productId: string) => void;
  onUpdateQuantity: (productId: string, quantity: number) => void;
  onUpdateTotal?: (productId: string, customTotal: number | undefined) => void;
  onClearOrder: () => void;
  onCheckout: () => void;
  isOpen: boolean;
  onClose: () => void;
  showReceipt?: boolean;
  receiptItems?: OrderItem[] | null;
  receiptPayment?: PaymentDetails | null;
  onCloseReceipt?: () => void;
}

export function OrderSidebar({ 
  items, 
  onRemoveItem, 
  onUpdateQuantity, 
  onUpdateTotal,
  onClearOrder,
  onCheckout,
  isOpen,
  onClose,
  showReceipt = false,
  receiptItems = null,
  receiptPayment = null,
  onCloseReceipt,
}: OrderSidebarProps) {
  const { products } = useMySQLSync();
  const [showServicesDialog, setShowServicesDialog] = useState(false);
  const [editingTotalItemId, setEditingTotalItemId] = useState<string | null>(null);
  const [totalEditValue, setTotalEditValue] = useState<string>("");
  const totalInputRef = useRef<HTMLInputElement>(null);
  
  // Helper to extract product name and variation from display name
  const getProductAndVariation = (productId: string, displayName: string) => {
    // First, try to extract variation from productId (most reliable method)
    if (productId && productId.includes('-') && products.length > 0) {
      const parts = productId.split('-');
      if (parts.length >= 2) {
        // Try to find base product by matching ID patterns
        // Strategy 1: First part is base ID
        const baseId = parts[0];
        let baseProduct = products.find(p => p.id === baseId);
        
        // Strategy 2: Product ID starts with base product ID
        if (!baseProduct) {
          baseProduct = products.find(p => productId.startsWith(p.id + '-'));
        }
        
        if (baseProduct) {
          // Try to find the variation
          const variations = baseProduct.variations || [];
          let parsedVariations: any[] = [];
          
          // Parse variations if string
          if (Array.isArray(variations)) {
            parsedVariations = variations;
          } else if (typeof variations === 'string') {
            try {
              parsedVariations = JSON.parse(variations);
            } catch {
              parsedVariations = [];
            }
          }
          
          // Try multiple strategies to find the variation
          const variation = parsedVariations.find((v: any) => {
            if (!v) return false;
            // Strategy 1: Match full variation ID
            const fullVariationId = `${baseProduct.id}-${v.id || v.name}`;
            if (fullVariationId === productId) return true;
            
            // Strategy 2: Match variation ID from productId parts
            const variationIdFromParts = parts.slice(1).join('-');
            if (v.id === variationIdFromParts || v.name === variationIdFromParts) return true;
            
            // Strategy 3: Match last part of productId
            const lastPart = parts[parts.length - 1];
            if (v.id === lastPart || v.name === lastPart) return true;
            
            return false;
          });
          
          if (variation) {
            // Get variation name (even if auto-generated)
            let variationName = variation.name ? variation.name.trim() : null;
            
            // If variation has a name, use it
            if (variationName) {
              // Check if it's auto-generated (contains price pattern)
              const isAutoGenerated = variationName.includes(' - ₱') && /₱\d+\.\d{2}$/.test(variationName);
              
              // For auto-generated, extract just the price part
              if (isAutoGenerated) {
                // Extract price from auto-generated name like "Product - ₱5.00"
                const priceMatch = variationName.match(/₱(\d+\.?\d*)/);
                if (priceMatch) {
                  variationName = `₱${priceMatch[1]}`;
    } else {
                  // If no price match, use the last part after " - "
                  const nameParts = variationName.split(' - ');
                  if (nameParts.length > 1) {
                    variationName = nameParts[nameParts.length - 1].trim();
                  }
                }
              }
              
              // Return product name and variation separately
              return { productName: baseProduct.name, variationName };
            } else {
              // Variation exists but no name - try to extract from productId or use variation ID
              const variationIdFromParts = parts.slice(1).join('-');
              if (variationIdFromParts && variationIdFromParts !== baseProduct.id) {
                // Try to use variation.id or variation.name as fallback
                const fallbackName = variation.id || variation.name || variationIdFromParts;
                return { productName: baseProduct.name, variationName: fallbackName };
              }
            }
          } else {
            // Variation not found in parsed variations, but productId suggests it's a variation
            // Try to use the part after the first dash as variation name
            const variationIdFromParts = parts.slice(1).join('-');
            if (variationIdFromParts && variationIdFromParts !== baseProduct.id) {
              return { productName: baseProduct.name, variationName: variationIdFromParts };
            }
          }
        }
      }
    }
    
    // Fallback: Check if display name contains variation pattern (e.g., "Product - Variation")
    if (displayName && displayName.includes(' - ')) {
      const nameParts = displayName.split(' - ');
      if (nameParts.length > 1) {
        const lastPart = nameParts[nameParts.length - 1].trim();
        // If it doesn't match price pattern, it's a variation
        const isPricePattern = /^₱?\d+\.?\d{0,2}$/.test(lastPart);
        if (!isPricePattern) {
          return {
            productName: nameParts.slice(0, -1).join(' - ').trim(),
            variationName: lastPart
          };
        } else {
          // It's a price pattern, so it might be an auto-generated variation
          return {
            productName: nameParts.slice(0, -1).join(' - ').trim(),
            variationName: lastPart
          };
        }
      }
    }
    
    // No variation found, return just the product name
    return { productName: displayName, variationName: null };
  };
  
  // Determine if receipt should be displayed - single source of truth
  const shouldShowReceipt = useMemo(() => {
    return showReceipt && receiptItems !== null && receiptItems.length > 0 && receiptPayment !== null;
  }, [showReceipt, receiptItems, receiptPayment]);

  // Calculate receipt totals
  const receiptSubtotal = useMemo(() => {
    if (!receiptItems) return 0;
    return receiptItems.reduce((sum, item) => {
    const productTotal = item.product.price * item.quantity;
    const servicesTotal = (item.selectedServices || []).reduce(
      (serviceSum, service) => serviceSum + service.price * item.quantity,
      0
    );
    return sum + productTotal + servicesTotal;
    }, 0);
  }, [receiptItems]);
  
  const receiptTotal = receiptSubtotal;
  const receiptItemCount = receiptItems?.reduce((sum, item) => sum + item.quantity, 0) || 0;
  const now = new Date();
  
  const subtotal = items.reduce((sum, item) => {
    // Use custom total if set, otherwise calculate
    if (item.customTotal !== undefined) {
      return sum + item.customTotal;
    }
    const productTotal = item.product.price * item.quantity;
    const servicesTotal = (item.selectedServices || []).reduce(
      (serviceSum, service) => serviceSum + service.price * item.quantity,
      0
    );
    return sum + productTotal + servicesTotal;
  }, 0);

  const total = subtotal;
  const itemCount = items.reduce((sum, item) => sum + item.quantity, 0);
  
  // Calculate total services fees
  const totalServicesFee = items.reduce((sum, item) => {
    return sum + (item.selectedServices || []).reduce(
      (serviceSum, service) => serviceSum + service.price * item.quantity,
      0
    );
  }, 0);
  
  // Get all services with details
  const servicesBreakdown = items.flatMap((item) => {
    if (!item.selectedServices || item.selectedServices.length === 0) return [];
    const { productName, variationName } = getProductAndVariation(item.product.id, item.product.name);
    return item.selectedServices.map((service) => ({
      productName,
      variationName,
      serviceName: service.name,
      servicePrice: service.price,
      quantity: item.quantity,
      total: service.price * item.quantity,
    }));
  });

  return (
    <>
      {/* Backdrop for mobile */}
      {isOpen && (
        <div 
          className="fixed inset-0 bg-background/80 backdrop-blur-sm z-40 lg:hidden"
          onClick={onClose}
        />
      )}
      
      {/* Sidebar */}
      <aside 
        tabIndex={-1}
        className={`
        fixed top-0 right-0 h-full w-full max-w-md glass-panel z-50
        transform transition-transform duration-300 ease-out
        ${isOpen ? 'translate-x-0' : 'translate-x-full'}
        lg:static lg:translate-x-0 lg:w-96 lg:rounded-lg lg:h-full
        perspective-1000
        focus:outline-none
      `}>
        {/* Flip Container */}
        <div 
          className="relative w-full h-full preserve-3d transition-transform duration-500 ease-in-out"
          style={{ 
            transformStyle: 'preserve-3d',
            transform: shouldShowReceipt ? 'rotateY(180deg)' : 'rotateY(0deg)'
          }}
        >
          {/* Cart Side (Front) */}
          <div 
            className="absolute inset-0 w-full h-full backface-hidden flex flex-col"
            style={{ 
              backfaceVisibility: 'hidden',
              display: shouldShowReceipt ? 'none' : 'flex'
            }}
          >
            {/* Header */}
            <div className="p-4 border-b border-border">
              <div className="flex items-center gap-3">
                <div className="relative p-2 bg-primary/20 rounded-lg">
                  <ShoppingCart className="w-5 h-5 text-primary" />
                  {itemCount > 0 && (
                    <span className="absolute -top-1.5 -right-1.5 min-w-5 h-5 flex items-center justify-center px-1.5 bg-primary text-primary-foreground text-xs font-bold rounded-full">
                      {itemCount}
                    </span>
                  )}
                </div>
                <div className="flex-1">
                  <h2 className="font-semibold text-foreground">Current Order</h2>
                  <p className="text-sm text-muted-foreground">{itemCount} items</p>
                </div>
                {/* Close button - mobile only */}
                <button 
                  onClick={onClose}
                  className="p-2 rounded-lg hover:bg-secondary lg:hidden"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>
            </div>

            {/* Items list */}
            <div className="flex-1 overflow-auto p-4 space-y-2">
              {items.length === 0 ? (
                <div className="text-center py-12 text-muted-foreground">
                  <ShoppingCart className="w-12 h-12 mx-auto mb-3 opacity-30" />
                  <p>No items yet</p>
                  <p className="text-sm mt-1">Start typing to add products</p>
                </div>
              ) : (
                items.map((item, index) => {
                  const servicesTotal = (item.selectedServices || []).reduce(
                    (sum, service) => sum + service.price * item.quantity,
                    0
                  );
                  const calculatedTotal = item.product.price * item.quantity + servicesTotal;
                  const itemTotal = item.customTotal !== undefined ? item.customTotal : calculatedTotal;
                  const isEditingTotal = editingTotalItemId === item.product.id;
                  
                  const { productName, variationName } = getProductAndVariation(item.product.id, item.product.name);
                  const displayName = variationName ? `${productName} - ${variationName}` : productName;
                  
                  return (
                    <div
                      key={`${item.product.id}-${index}-${(item.selectedServices || []).map(s => s.id).join(',')}`}
                      className="flex items-center gap-2 p-2 bg-secondary/50 rounded hover:bg-secondary transition-colors"
                    >
                      {/* Product Name */}
                        <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium text-foreground truncate">
                          {displayName}
                          </p>
                            </div>
                      
                      {/* Quantity Controls */}
                      <div className="flex items-center gap-1">
                          <button
                            onClick={() => onUpdateQuantity(item.product.id, item.quantity - 1)}
                          className="p-1 rounded hover:bg-muted text-muted-foreground hover:text-foreground transition-colors"
                          >
                          <Minus className="w-3.5 h-3.5" />
                          </button>
                        <span className="w-8 text-center font-mono text-sm font-bold text-foreground">
                            {item.quantity}
                          </span>
                          <button
                            onClick={() => onUpdateQuantity(item.product.id, item.quantity + 1)}
                          className="p-1 rounded hover:bg-muted text-muted-foreground hover:text-foreground transition-colors"
                          >
                          <Plus className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      
                      {/* Price - Editable */}
                      {isEditingTotal && onUpdateTotal ? (
                        <Input
                          ref={totalInputRef}
                          type="number"
                          step="0.01"
                          min="0"
                          value={totalEditValue}
                          onChange={(e) => setTotalEditValue(e.target.value)}
                          onBlur={() => {
                            const numericValue = parseFloat(totalEditValue);
                            if (!isNaN(numericValue) && numericValue >= 0) {
                              onUpdateTotal(item.product.id, numericValue !== calculatedTotal ? numericValue : undefined);
                            } else {
                              onUpdateTotal(item.product.id, undefined);
                            }
                            setEditingTotalItemId(null);
                            setTotalEditValue("");
                          }}
                          onKeyDown={(e) => {
                            if (e.key === 'Enter') {
                              const numericValue = parseFloat(totalEditValue);
                              if (!isNaN(numericValue) && numericValue >= 0) {
                                onUpdateTotal(item.product.id, numericValue !== calculatedTotal ? numericValue : undefined);
                              } else {
                                onUpdateTotal(item.product.id, undefined);
                              }
                              setEditingTotalItemId(null);
                              setTotalEditValue("");
                            } else if (e.key === 'Escape') {
                              setEditingTotalItemId(null);
                              setTotalEditValue("");
                            }
                          }}
                          className="w-20 h-7 text-xs font-mono text-right px-1"
                          autoFocus
                        />
                      ) : (
                        <button
                          onClick={() => {
                            if (onUpdateTotal) {
                              setEditingTotalItemId(item.product.id);
                              setTotalEditValue(itemTotal.toFixed(2));
                              setTimeout(() => totalInputRef.current?.focus(), 0);
                            }
                          }}
                          className={`font-mono font-semibold text-sm min-w-[60px] text-right hover:underline transition-colors ${
                            item.customTotal !== undefined ? 'text-warning' : 'text-primary'
                          }`}
                          title={item.customTotal !== undefined ? "Click to edit (custom price)" : "Click to edit price"}
                        >
                          ₱{itemTotal.toFixed(2)}
                          {item.customTotal !== undefined && <Edit2 className="w-3 h-3 inline ml-1" />}
                        </button>
                      )}
                      
                      {/* Remove Button */}
                      <button
                        onClick={() => onRemoveItem(item.product.id)}
                        className="p-1 rounded hover:bg-destructive/20 text-destructive transition-colors shrink-0"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  );
                })
              )}
            </div>

            {/* Footer with total and actions */}
            <div className="p-4 border-t border-border space-y-4 bg-background/50">
              {totalServicesFee > 0 && (
                <button
                  onClick={() => setShowServicesDialog(true)}
                  className="w-full text-xs text-primary hover:text-primary/80 hover:underline transition-colors flex items-center justify-center gap-1"
                >
                  <Info className="w-3 h-3" />
                  <span>Services: ₱{totalServicesFee.toFixed(2)}</span>
                </button>
              )}
              <div className="flex items-center justify-between">
                <span className="text-lg font-medium text-muted-foreground">Total</span>
                <span className="text-3xl font-bold font-mono text-primary">
                  ₱{total.toFixed(2)}
                </span>
              </div>
              
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  className="flex-1"
                  onClick={onClearOrder}
                  disabled={items.length === 0}
                >
                  Clear
                </Button>
                <Button 
                  className="flex-1 glow-primary text-lg py-6"
                  onClick={onCheckout}
                  disabled={items.length === 0}
                >
                  Checkout
                </Button>
              </div>
            </div>
          </div>
          
          {/* Receipt Side (Back) - Always rendered, just hidden when not needed */}
          <div 
            className="absolute inset-0 w-full h-full backface-hidden flex flex-col"
            style={{ 
              backfaceVisibility: 'hidden',
              transform: 'rotateY(180deg)',
              display: shouldShowReceipt ? 'flex' : 'none'
            }}
          >
              {/* Receipt Header */}
              <div className="p-4 border-b border-border">
                <div className="flex items-center gap-3">
                  <div className="relative p-2 bg-success/20 rounded-lg">
                    <CheckCircle className="w-5 h-5 text-success" />
                  </div>
                  <div className="flex-1">
                    <h2 className="font-semibold text-foreground">Receipt</h2>
                    <p className="text-sm text-muted-foreground">Transaction Complete</p>
                  </div>
                  <button 
                    onClick={() => {
                      if (onCloseReceipt) onCloseReceipt();
                    }}
                    className="p-2 rounded-lg hover:bg-secondary lg:hidden"
                  >
                    <X className="w-5 h-5" />
                  </button>
                </div>
              </div>

              {/* Receipt Content */}
              <div className="flex-1 overflow-auto p-4">
                <div className="bg-card border border-border rounded-lg p-4 font-mono text-sm">
                  <div className="header text-center mb-4">
                    <h1 className="text-lg font-bold text-foreground">Sari-Sari Store</h1>
                    <p className="text-muted-foreground text-xs">
                      {now.toLocaleDateString("en-PH", {
                        weekday: "long",
                        year: "numeric",
                        month: "long",
                        day: "numeric",
                      })}
                    </p>
                    <p className="text-muted-foreground text-xs">
                      {now.toLocaleTimeString("en-PH")}
                    </p>
                  </div>

                  <div className="divider border-t border-dashed border-border my-3" />

                  <div className="space-y-2">
                  {receiptItems?.map((item) => {
                      const servicesTotal = (item.selectedServices || []).reduce(
                        (sum, service) => sum + service.price * item.quantity,
                        0
                      );
                      const itemTotal = item.product.price * item.quantity + servicesTotal;
                      
                      return (
                        <div key={item.product.id} className="item flex justify-between text-foreground">
                          <div className="flex-1 min-w-0">
                          {(() => {
                            const { productName, variationName } = getProductAndVariation(item.product.id, item.product.name);
                            return (
                              <>
                                <div className="truncate">{productName}</div>
                                {variationName && (
                                  <div className="text-xs text-muted-foreground truncate mt-0.5">
                                    {variationName}
                                  </div>
                                )}
                              </>
                            );
                          })()}
                            {item.selectedServices && item.selectedServices.length > 0 && (
                              <div className="text-xs text-muted-foreground mt-0.5">
                                {item.selectedServices.map(s => s.name).join(', ')}
                              </div>
                            )}
                          </div>
                          <span className="w-10 text-center text-muted-foreground">×{item.quantity}</span>
                          <span className="w-20 text-right">
                            ₱{itemTotal.toFixed(2)}
                          </span>
                        </div>
                      );
                    })}
                  </div>

                  <div className="divider border-t border-dashed border-border my-3" />

                  <div className="space-y-1 text-sm">
                    <div className="flex justify-between text-foreground">
                      <span>Subtotal</span>
                      <span>₱{receiptSubtotal.toFixed(2)}</span>
                    </div>
                    <div className="divider border-t border-dashed border-border my-2" />
                    <div className="flex justify-between text-lg font-bold text-primary">
                      <span>Total</span>
                      <span>₱{receiptTotal.toFixed(2)}</span>
                    </div>
                  </div>

                  <div className="divider border-t border-dashed border-border my-3" />

                  <div className="space-y-2 text-xs">
                    <div className="flex items-center gap-2 text-muted-foreground">
                    {receiptPayment?.method === 'cash' ? (
                        <Banknote className="w-4 h-4" />
                      ) : (
                        <Smartphone className="w-4 h-4" />
                      )}
                      <span className="font-medium">
                      {receiptPayment?.method === 'cash' ? 'Cash' : 'GCash'}
                      </span>
                    </div>
                  {receiptPayment?.amountTendered && (
                      <div className="flex justify-between text-foreground">
                        <span>Amount Paid</span>
                        <span>₱{receiptPayment.amountTendered.toFixed(2)}</span>
                      </div>
                    )}
                  {receiptPayment?.change && receiptPayment.change > 0 && (
                      <div className="flex justify-between text-foreground">
                        <span>Change</span>
                        <span>₱{receiptPayment.change.toFixed(2)}</span>
                      </div>
                    )}
                  </div>

                  <div className="footer text-center mt-4 text-muted-foreground text-xs">
                    <p>Thank you for your purchase!</p>
                    <p>Please come again</p>
                  </div>
                </div>
              </div>

              {/* Receipt Footer */}
              <div className="p-4 border-t border-border bg-background/50">
                <Button 
                  className="w-full"
                  onClick={() => {
                    if (onCloseReceipt) onCloseReceipt();
                  }}
                >
                  Close
                </Button>
              </div>
            </div>
        </div>
      </aside>

      {/* Services Breakdown Dialog */}
      <Dialog open={showServicesDialog} onOpenChange={setShowServicesDialog}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Services Breakdown</DialogTitle>
          </DialogHeader>
          <div className="space-y-3 mt-4">
            {servicesBreakdown.length === 0 ? (
              <p className="text-sm text-muted-foreground text-center py-4">
                No services applied
              </p>
            ) : (
              <>
                {servicesBreakdown.map((service, index) => (
                  <div
                    key={index}
                    className="p-3 bg-secondary/30 rounded-lg border border-border/50"
                  >
                    <div className="flex items-center justify-between mb-1">
                      <div className="flex-1 min-w-0">
                        <span className="text-sm font-medium text-foreground block truncate">
                        {service.productName}
                      </span>
                        {service.variationName && (
                          <span className="text-xs text-muted-foreground block truncate mt-0.5">
                            {service.variationName}
                          </span>
                        )}
                      </div>
                      <span className="text-xs text-muted-foreground ml-2 shrink-0">
                        Qty: {service.quantity}
                      </span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-xs text-muted-foreground">
                        {service.serviceName}
                      </span>
                      <span className="text-sm font-mono text-primary">
                        ₱{service.servicePrice.toFixed(2)} × {service.quantity} = ₱{service.total.toFixed(2)}
                      </span>
                    </div>
                  </div>
                ))}
                <div className="pt-3 border-t border-border">
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-semibold text-foreground">
                      Total Services/Fees
                    </span>
                    <span className="text-lg font-mono font-bold text-primary">
                      ₱{totalServicesFee.toFixed(2)}
                    </span>
                  </div>
                </div>
              </>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
