import { Product } from "@/types/product";

/**
 * Get the full display name for a product, including variation if applicable
 * @param productId - The product ID (may contain variation ID as "baseId-variationId")
 * @param storedName - The name stored in the sale/item record
 * @param products - Array of all products to look up variation info
 * @returns Full display name with variation (e.g., "Product Name - Variation Name")
 */
export function getProductDisplayName(
  productId: string,
  storedName: string,
  products: Product[]
): string {
  // If stored name already includes variation (has " - " and doesn't end with price), use it
  if (storedName && storedName.includes(' - ')) {
    const nameParts = storedName.split(' - ');
    const lastPart = nameParts[nameParts.length - 1].trim();
    // If last part doesn't look like a price (₱X.XX or just numbers), it's likely a variation
    if (!/^₱?\d+\.?\d{0,2}$/.test(lastPart)) {
      return storedName; // Already has variation
    }
  }

  // Check if productId contains variation ID (format: "baseId-variationId")
  if (productId && productId.includes('-')) {
    const parts = productId.split('-');
    if (parts.length >= 2) {
      // Try different splitting strategies
      // Strategy 1: Last part is variation ID
      const possibleVariationId = parts[parts.length - 1];
      const possibleBaseId = parts.slice(0, -1).join('-');
      
      // Strategy 2: First part is base ID, rest is variation ID
      const baseId = parts[0];
      const variationId = parts.slice(1).join('-');
      
      // Try to find base product
      let baseProduct = products.find(p => p.id === possibleBaseId || p.id === baseId);
      
      if (!baseProduct) {
        // Try matching by checking if any product ID starts with the base part
        baseProduct = products.find(p => productId.startsWith(p.id + '-'));
      }
      
      if (baseProduct) {
        // Try to find the variation
        const variations = baseProduct.variations || [];
        let parsedVariations: any[] = [];
        
        // Parse variations if string
        if (Array.isArray(variations)) {
          parsedVariations = variations;
        } else if (typeof variations === 'string') {
          try {
            parsedVariations = JSON.parse(variations);
          } catch {
            parsedVariations = [];
          }
        }
        
        // Try to find variation by ID or by matching the full productId
        let variation = parsedVariations.find((v: any) => {
          if (!v) return false;
          const fullVariationId = `${baseProduct.id}-${v.id || v.name}`;
          return (
            v.id === possibleVariationId ||
            v.id === variationId ||
            v.name === possibleVariationId ||
            v.name === variationId ||
            fullVariationId === productId
          );
        });
        
        if (variation && variation.name) {
          const variationName = variation.name.trim();
          // Check if variation name is auto-generated (contains price pattern)
          const isAutoGenerated = variationName && 
            variationName.includes(' - ₱') && 
            /₱\d+\.\d{2}$/.test(variationName);
          
          if (!isAutoGenerated && variationName) {
            // Return "Product Name - Variation Name"
            return `${baseProduct.name} - ${variationName}`;
          } else if (variationName) {
            // Auto-generated, but still include it
            return `${baseProduct.name} - ${variationName}`;
          }
        }
      }
    }
  }
  
  // Fallback to stored name
  return storedName || 'Unknown Product';
}

